language: php

php:
  - 5.6

install:
  - composer install --no-interaction --prefer-dist

#before_script: phpenv config-add myconfig.ini

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec run

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
